### ISSUE TITLE
generate chord names

### ISSUE THREAD

**Issue by garfieldnate** [mikehadlow/gtr-cof#28] opened 2018-09-15 08:33 UTC
For example, if select C, E-flat, G, and B-flat, then it would display "Cm7" somewhere.

**Comment by mikehadlow** [comment] 2018-09-16 08:59
Good idea. It would have to work for all possible combinations though.

**Comment by mikehadlow** [comment] 2020-11-24 08:59
Duplicate of #42. Closing this because the other has more detail.

**Closed by mikehadlow** 2020-11-24 08:59 UTC
Labels: enhancement
